name: Scrape Guide Release

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: preview

      - name: Run scraper (writes guide.json to repo root)
        run: dotnet run --configuration Release --project ./AndyTV.Guide.Scraper/AndyTV.Guide.Scraper.csproj

      - name: Create or update "guide" release and upload asset
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create guide || true
          gh release upload guide guide.json --clobber
