name: guide

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: preview

      - name: Run scraper (writes out/guide.json)
        run: dotnet run -c Release --project ./AndyTV.Guide.Scraper/AndyTV.Guide.Scraper.csproj

      - name: Checkout aherrick.github.io
        uses: actions/checkout@v4
        with:
          repository: aherrick/aherrick.github.io
          path: site
          token: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Copy guide.json and push
        run: |
          mkdir -p site/AndyTV
          cp out/guide.json site/AndyTV/guide.json
          cd site
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add AndyTV/guide.json
          git diff --cached --quiet || git commit -m "Update guide.json"
          git push
