name: nuget-outdated

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Midnight UTC nightly

jobs:
  nuget-outdated:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for outdated NuGet packages
        uses: aherrick/nuget-outdated@main
        with:
          #Ignore VLC for now, it seems buggy and we don't want to update it until we can test it more thoroughly
          ignore: 'AndyTV=Velopack&AndyTV=VideoLAN.LibVLC.Windows'
          includeprelease: 'true'
          currentmajorprereleaseonly: 'true'
